from . import property
from . import owner
from . import res_partner
from . import property_history
from . import wizard
from . import property_comparison
from . import building
from . import offer
from . import employee
from . import renter